open-afc-project/openafc

src/afc-packages/afcworker/afc_worker.py, tools/rcache/compose_rcache.yaml
- Explicitly disabled unused parameters in RcacheClientSettings() in worker to void their trickling from environment variables (and causing initialization failure)
- Renamed RCACHE_PORT to RCACHE_CLIENT_PORT in compose_rcache.yaml
=> 7. Kubernetes-related changes

als/Dockerfile.siphon, cert_db/Dockerfile, msghnd/Dockerfile, rat_server/Dockerfile, worker/Dockerfile.preinstall
Alpine module for confluent-kafka became irrelevant, hence in all pertinent dockerfiles its installation was changed from module install to librdkafka odue install and pip-install of confluent-kafka
=> 25. Fixing confluent-kafka client obtaining

tests/regression/regression.sh
In recent changes build directory of ALS Siphon image was changed frol als to source files' root, which was not properly reflected in tests/regression/regression.sh This RB fixes the problem
=> 43. Fixed ALS Siphon build failure

helm/afc-ext/values.yaml, helm/afc-int/values.yaml, helm/bin/install_prerequisites.py, helm/bin/install_prerequisites.yaml
Done to accommodate site-specific scripts' restructuring:
- Announced that push image repositories may be defined in (overrides of) in values.yaml
- List of prerequisites to install may be defined in override of install_prerequisites.yaml
- Script-only (install-only) components are allowed in install_prerequisites.yaml
=> 58. Moving some helm/bin scripts' command line parameters to YAML files

msghnd/entrypoint.sh, rat_server/entrypoint.sh, worker/docker-entrypoint.sh
Several services not able to handle TERM signal correctly in the current Dockerfile entrypoint script implementation so that containers are directly killed.    
Msghnd, Worker and Rat-server entrypoint.sh are enhanced for supporting graceful shutdown.  
Testing info please refer to https://github.com/open-afc-project/openafc/issues/69
=> 69. Graceful shutdown enhancement

dispatcher/Dockerfile, dispatcher/nginx.conf.template, helm/afc-common/templates/_helpers.tpl, helm/afc-ext/values.yaml, helm/afc-int/values.yaml, helm/monitoring/prometheus_ingress/prometheus-ingress.yaml, tests/requirements.txt
- In dispatcher passthroughs added for Grafana and Prometheus on ports 3000 and 9090 respectively. They are controlled by environment variables:
- AFC_PROMETHEUS/GRAFANA_TARGET - host/service name:port
- AFC_PROMETHEUS/GRAFANA_PATH - path to root (may be nontrivial if target is behind ingress-nginx)
- AFC_PROMETHEUS/GRAFANA_ENABLED - enabled/disabled (disabled by default)
- These environment variables also added to values.yaml foe internal (k3d) and external (k3d) clusters
- Ingress for Prometheus (that lives in monitoring namespace) added separately (to be installed in monitoring namespace)
- ingress data in values.yaml changed from list of rules to dictionary of rules to facilitate partial overriding. _helpers.tpl changed accordingly
Seemingly works on k3d
=> 62. Add optional dispatcher passthroughs for Grafana and Prometheus

helm/bin/install_prerequisites.py, helm/bin/install_prerequisites.yaml, helm/bin/k3d_registry.py, helm/bin/utils.py
- helm installation reordered so that `helm install` immediately follows `preinstall`. This allow to install prometheus adaadapter before resurrection of removed metrics apiservice 
- `attempts` - used in prometheus-adapter indtallation to kope with resurrection of metrics apiservice
- `has_service` renamed to `manifest_check` to check for anything (not necessary service) - used in installation of prometheus_ingress
- `helm_wait` renamed to `install_wait' to wait for manifest installation
- {{context:kubectl}} used in kubectl preinstall/postinstall clauese
=> 72. Fixing Kubernetes install problems and bugs

dispatcher/Dockerfile, dispatcher/acceptor.py, dispatcher/entrypoint.sh
- acceptor.py getting nginx binary name in NGINX_BIN environment variables and uses it for:
- Addressing nginx (e.g. when restarting it)
- Checking if nginx is running in readiness check procedure
- Checking if nginx is running at the beginning of run procedure - and crashes dispatcher pod if it is not running
- Healtcheck procedure changed in Dockerfile. It is not actually used in Kubernetes (and ignored in Docker), so it just serves an illustrative purpose
=> 83. Crash dispatcher if nginx not started

dispatcher/Dockerfile, dispatcher/nginx.conf.template, helm/bin/k3d_cluster_create.py, helm/monitoring/prometheus/prometheus-main.yaml, helm/monitoring/prometheus_adapter/values-prometheus_adapter.yaml, helm/monitoring/prometheus_ingress/prometheus-ingress.yaml, prometheus/Dockerfile-grafana, prometheus/grafana.ini
Grafana and Prometheus seemingly can't be politically correctly exposed on their respective ports, so they are being moved to /grafana and /prometheus on ports 80/443
This requires reconfiguration of dispatcher (as endpoints are changed and prometheus requires extension of security policy), grafana/prometheus (as they should be informed that they are exposed on nonroot endpoints - this is necessary as they both heavily use redirects) and entities that use them (for now it is Prometheus Adapter)
=> 88.  Exposing Prometheus and Grafana on endpoints

dispatcher/nginx.conf.template, helm/afc-int/values-k3d.yaml, helm/afc-int/values.yaml, prometheus/grafana.ini
'unsafe-inline', recently added to Content-Security-Policy of script-src to expose Prometheus and Grafana moved to Prometheus/Grafana location block to avoid further discussion.
Grafana parameters fixed to make it work both behind Dispatcher-only (k3d) and Dispatcher+ingress-nginx (GCE)
=> 94. Revising nginx settings for Grafana and Prometheus

helm/afc-common/templates/_helpers.tpl, helm/afc-int/values.yaml
- Timeout-related annotations added to ingress parameters of msghnd in values.yaml (unfortunately there is no easy way to parameterize them, so just a relatively long 15 minutes were chosen)
- Ingress annotation rendering bug fixed in _helpers.tpl
=> 99. Increasing ingress-nginx timeout for msghnd

ReleaseNote.md, src/afc-engine/AfcManager.cpp
Issue 102
Fixing anomalous FS Rx Gain should be all done by the FS parser during generation of the FS database sqlite3 file. Recently, a bug was found where the afc-engine removed Canadian FS links with FS Rx Gain < 10 dBi. We hadn't seen this in the US AFC since the FS parser implements WinnForum TS 1014 R2-AIP-05 and 06 that ensures FS Rx Gain is at least 32 dBi. However, for Canada, the FS database is assumed to be sanitized already and minimum fix is done by the FS Parser (only if the gain is missing or 0). This check by the afc-engine has now been removed.
Ran a test (see attached afc-config, request and response json files to the issue) and confirmed that the fs_anom.csv file is empty as expected. Previously, this file contained 23 links for this test that were removed due to having …
=> 102 remove anomalous fs rxgain check

ReleaseNote.md, src/afc-engine/AfcManager.cpp
Code modifications to the afc-engine that optimize speed performance broke the exc_thr file. The underlying issue is that printing to the exc_thr will require re-computation of some parameters and thus undermine the optimizations to some extent. 
Ran a test [FSP1 but for 20 MHz channels only] (see attached afc-config, request and response json files and exc_thr files to the issue) and validated that the updated exc_thr would now show the links with distance > 1km using ITM (rather the FSPL that was tried originally to determine whether the regulatory threshold is exceeded or not) (previously, only the FSPL ones were shown). When printSkippedLinks flag in AFC Config is set, links that pass the regulatory threshold with FSPL are shown as well. Note that when the printSkippedLinks flag is …
=> 105 fix exc thr file

src/afc-packages/afcmodels/afcmodels/__init__.py, src/afc-packages/afcmodels/afcmodels/aaa.py, src/afc-packages/afcmodels/afcmodels/hardcoded_relations.py, src/afc-packages/rcache/rcache_req_cfg_hash.py, src/afc-packages/rcache/setup.py, src/ratapi/ratapi/manage.py, src/ratapi/ratapi/views/admin.py, src/ratapi/ratapi/views/ratafc.py, src/ratapi/ratapi/views/ratapi.py
- afc-packages/afmodels/afcmodels/hardcoded_relations.py introduced. It contains following hardcoded (DB-worthy) stuff from ratafc/ratapi:
- RulesetVsRegion class that encapsulates conversion between regionStr of AFC Config and Ruleset IDs of AFC requests/responses
- SpecialCertifications class that encapsulates properties of special certification IDs and serial numbers
- VendorExtensionFilter class that encapsulates whitelists of Vendor Extensions, used in AFC requests/responses
- afc-packages/rcache/rcache_req_cfg_hash.py introduced that encapsulates computation of request/config hash (key in Rcache database)
- Corresponded code removed from ratapo.py and ratafc.py
- Mentioned above classes applied in manage.py, admin.py. ratapi.py, ratafc.py
Regression tests passed, cached load test …
=> 116. Extract DB/Rcache hardcoded stuff into modules, shareable with new msghnd implementation

helm/afc-int/templates/deployment-afcserver.yaml, helm/afc-int/templates/deployment-msghnd.yaml, helm/afc-int/templates/hpa-afcserver.yaml, helm/afc-int/templates/hpa-worker.yaml, helm/afc-int/templates/ingress-afcserver.yaml, helm/afc-int/templates/podmonitor-msghnd.yaml, helm/afc-int/templates/service-afcserver.yaml, helm/afc-int/templates/service-msghnd.yaml, helm/afc-int/values-msghnd.yaml, helm/afc-int/values.yaml, helm/bin/helm_install_ext.py, helm/bin/helm_install_int.py, helm/bin/install_prerequisites.py, helm/bin/install_prerequisites.yaml, helm/bin/utils.py
- values.yaml have got afcserver section and sharedEnv.afc-req-service for switching between afcserver and msghnd
- afcserver's helmcharts (deployment, service, ingress, hpa) added
- values.msghnd.yaml added. It contains values.yaml patches to switch from afcserver to msghnd
- helm_install_int.py have got --msghnd to use msghnd instead of afcserver
- helm_install_*.py now wait for uninstallation completion
- install_prerequesites.yaml have got postuninstall clause in component section (used to strip istio from namespace)
=> 122. Adding afcserver and sme improvements into helm/

afc_server/afc_server_app.py
Because it makes logs less noisy (RMQ connection on start always fails as afcserver starts before RMQ)
=> 130. Postpone RMQ connection until first AFC request

helm/afc-int/values.yaml, src/ratapi/ratapi/manage.py, src/ratapi/ratapi/views/ratafc.py
- manage.py, ratafc.py: CertId.INDOOR changed to CERT_ID_LOCATION_INDOOR. Somehow itr slipped from my attention earlier
- values.yaml: Value for AFC_SERVER_PORT is taken from port service settings to avoid duplication of constant
Closes #132
=> 132. Afcserver-related bugfixes

src/afc-packages/appconfig/appcfg.py
In hopoe that it would prevent crashes on stale RatDB connections (like it did in case of Rcache)
Closes #138
=> 138. Adding pool_pre_ping=True SqlAlchemy engine creation parameter

.github/workflows/regressions-test-remote.yml, tests/regression/run_tests.sh
It runs afc_tests.py --webui on some tests to make sure that WebUI backend still functions
=> 152. 'run ngnx-rat_server-rmq-worker path tests' step added to github regression tests

tools/load_tool/afc_load_tool.py, tools/load_tool/afc_load_tool.yaml
- Added --rate_print-sec command line switch that prints instantaneous rate at regular intervals
- Added --code command line switch that explicitly specifies HTTP return code for `netload` operation
- Added --all command line switch for `load` to run sequentially through given index range - as a replacement for unavailable `preload` operation
- Replace access to 'msghnd' with access to `afcserver` (for k3d and compose platforms)
Closes #155
=> 155. afc_load_tool.py improvements

helm/afc-int/values-k3d.yaml, helm/bin/helm_install_ext.py, helm/bin/install_prerequisites.py, helm/bin/utils.py
- values-k3d.yaml: default k3d hostpath for objstore added
- helm_install_ext.py, utils.py: wait for service termination added to wait_termination() and used to wait for dispatcher service termination
- install_prerequisites.py: ability to override list config items with nulls (to remove existing lists, not adding to them) added
=> 156. Helm improvements

helm/afc-ext/values-devel.yaml, helm/afc-ext/values.yaml, helm/afc-int/templates/deployment-dispatcher.yaml, helm/afc-int/templates/externalsecret-server-cert.yaml, helm/afc-int/values-devel.yaml, helm/afc-int/values-k3d.yaml, helm/afc-int/values.yaml, helm/bin/helm_install_ext.py, helm/bin/helm_install_int.py, helm/bin/k3d_cluster_create.py, helm/bin/push_images.py, tools/secrets/README.md, tools/secrets/templates/afc_secrets.yaml
- helm_install_*.py's --access_log replaced with --devel that enables Gery's development features in pods where they are enabled
- Brought server-cert secret to k3d platform
- Removed helm_install_*.py's --print_vaalues, as it does not quite work
Closes #165
=> 165. Helm improvements

tests/regression/regression.sh
build_dev_server() of regresion.sh changed:
- PIDs of each background build collected in build_pids array
- Image names are collected in parallel array build_names
- Upon process completion - exit codes are checked and names of failed images collected in failed_images array
- If there are any failed images - they are reported and function failed
Closes #167
=> 167. Make build_imgs.sh fail on build failures. Attempt 2

helm/afc-int/values.yaml, tests/regression/docker-compose.yaml, tests/regression/regression.sh
Because this entity has 3 names (rat-server, webui, afcserver) which is two too much. Also SRV in regression.sh renamed to WEBUI
Most of changes in regression.sh are from #167 to simplify future merging.
Checked on k3d.
This RB is draft because #167 should be merged first. Other than that it is good to go.
Closes #171.
=> 171. Renaming afc-server image to webui-image

helm/bin/install_prerequisites.yaml
Because the latest (v0.10.4) does not load
=> 178. External-secrets version fixed at v0.10.3

afc_server/afc_server_msg_proc.py
Without it ALS logging not performed, with it ALS logging is performed.
Closes #190
=> 190. ALS initialization added to afcerver

rcache/rcache_service.py
That was the only damage made by this typo
Result tested in Compose
=> 187. Typo fixed that prevented Rcache invalidation logging

als/als_siphon.py
These tables werte lwft empty dur to oversight.
This RB contains a couple of bugfixes that makes these tables filled
Closes #194
=> 194. Generation of PSD and EIRP tables in ALS database

tools/release/tag.sh
add script that makes tag and pushes the repository released containers
once the containers are built and tested, run script which creates tags (including :latest ) and pushes images to the repo
/opt/afc/tools/tag.sh from_tag release_tag
Were: 
from_tag is temporal image tag 
release_tag is new release tag version
=> 222 add script that makes tag and pushes the repository released containers

als/README.md, als/als_query.py, src/ratapi/ratapi/manage.py, src/ratapi/ratapi/util.py
- Some parameters of 'als_query.py als' command now may be specified several times and/or negated (with '-' prefix for value)
- AFC Config are ALS JSON logged as JSONs, not as strings
Closes #234
=> 234. ALS Logging improvements

als/als_migrations/versions/2024_10_31-87a874c761f8_mtls_dn_table_added.py
It is declared as Text in ALS.sql, but somehow this did not create problem with Postgres from containers.
GCE Postgres however treat this as an error, so type in Alembic script changed to Text
Closes #240
=> 240. Changing mtls_dn.dn_text column type from String to Text in Alembic upgrade script

als/Dockerfile.siphon, cert_db/Dockerfile, cert_db/entrypoint.sh, cert_db/requirements.txt, cert_db/sweep.sh, src/afc-packages/pkgs.cert_db, src/ratapi/ratapi/manage.py, src/ratapi/ratapi/views/ratafc.py
- Crashes, caused by dependencies of ratafc, included by rat-manage-api fixed
- Certificate retrievals rest invocations now have timeouts, set by REQUEST_TIMEOUT_SEC
- List of regions to sweep made configurable via REQUEST_TIMEOUT_SEC
- Sweep periodicity made configurable via REQUEST_TIMEOUT_SEC
- First invocation of sweep.sh is always in foreground, to make it crash and burn explicitly
- Healthcheck, based on last successful sweep added
=> 257.  cert_db fixes and improvements

uls/uls_service.py, uls/uls_service_healthcheck.py, uls/uls_service_state_db.py
datetime.utcnow() produce timezoneless timetag that breaks healtcheck and Grafana dashboards.
Replacing with datatime.now(timezone.utc)
=> 269. Adding timezones to ULS-related timetags

src/afc-engine/AfcManager.cpp, src/afc-engine/cconst.cpp, src/afc-engine/polygon.cpp
- AfcEngine.cpp:
- Signed/unsigned comparisons (mainly iteration over vectrors with integer indices) explicitly casted to size_t
- Unused variables commented out
- polygon.cpp: Signed/unsigned comparisons (iteration vectrors with integer indices) explicitly casted to size_t
- cconst.cpp: Missing names for enum values added
Closes #281
=> 281. AFC Engine facelift

src/afc-packages/rcache/rcache_db.py
Previously it was in migration scripts only.
Checked in compose environment on both newly created database and on previously created without extension.
Closes #295
=> 295. PostGIS extension for newly created rcache database added

rcache/Dockerfile
Absent migrations files caused rcache crashg and a lot of worker log messages (that require separate investigation)
=> 307. Rcache alembic migrations copy to docker image restored

als/als_siphon.py, src/afc-packages/als/als.py
- als.py -- pylint/pyright facelift
- als_siphon.py:
- select results are iterated via fetchall() (not directly), to achieve dictionary-style retrieval
- Decode error message in TableUpdaterBase supplied with table name
- Bug in RequestResponseTableUpdater, happened when more than one row being updated fixed
- Occasional Kafka message drops fixed
- DbFormatError intercepted, logged, metrics updated
Closes #304
=> 304. ALS-related bugfixes

als/ALS.sql, als/als_db_schema/ALS.dbml, als/als_db_schema/ALS_raw.sql, als/als_migrations/versions/2025_04_29-31179a635942_add_index_for_month_idx_columns.py
month_idx column will be used in ALS tables' partitioning, it requires its own index
Closes #348
=> 348. Add index for month_idx columns of all ALS database tables

rat_server/entrypoint.sh, src/ratapi/ratapi/manage.py, src/ratapi/ratapi/migrations/versions/9fba1618496f_downloaded_field_added_to_cert_id_table.py
- 9fba1618496f_downloaded_field_added_to_cert_id_table.py - typo fixed, now upgrade works as expected
- manage.py - typo fixed. Now rat-manage-api db-upgrade doesn't crash upon completion
- entrypoint.sh - alembic upgrade enforced on startup
Closes #350
=> 350. Fixing rat database upgrade bug

afc_server/afc_server_db.py, src/ratapi/ratapi/manage.py, src/ratapi/ratapi/views/ratafc.py
1. Layout of certificate flags in cert_id of ratdb reverted to original outdoor or indoor+outdoor. Actually only the preence of 'indoor' flag is important, but the very existence of outdoor flag makes it logical to use it with every certificate
2. afc_server and maghnd changed to not making any rejections based on indoor/outdoor certificate flags. They only convey indoor flag to AFC Engine
Checked with load tool that uses both indoor and outdoor certificates - no rejections.
Closes #358
=> 358. Indoor/outdoor certificate handling change

docker-compose.yaml, rat_server/entrypoint.sh
If rat_server container starts before ratdb, it skips ratdb alembic upgrade procedure and proceeds with new code on old database structure.
To avoid this problem, failure of ratdb creation/upgrade on rat_server startup cause container termination.
To facilitate its restart (on the moment when ratdb server is, hopefully, ready), rat_server set to autorestart in docker-compose.yaml.
Tested by adding artificial delay before Postgres start in ratdb container. After couple of restarts rat_server starts normally when ratdb become available.
Closes #356
=> 356. Probe ratdb database on rat_server start

ReleaseNote.md, src/coalition_ulsprocessor/src/uls-script/StationDataCA.h, src/coalition_ulsprocessor/src/uls-script/UlsFileReader.cpp
Updated the uls-script C++ program to filter on both "Service" (=9) and "ITU Class of Station" (=RA) to consider a link to be a radio astronomy site (RAS).
**Testing Done**
* Reviewed the latest generated RAS database by ULS Parser and confirmed that only the one Canadian RAS link (per the latest Stations Data Extracts) is added and the other two link (Service=9, Subservice = TC) are not added to the FS or RAS database.
* Ran four tests:
* Test 1: a point over the first link (service=9, ITU Class of Station=TC, authorization number=011013568-002) that shouldn't be protected in Canada, requesting all frequencies and channels. Confirmed from results.kmz file that there are no RAS at the both this link and the second link that shouldn't be protected.
* Test 2: a point over the same link as …
=> 373 update uls parser to properly parse updated iseds stations data extract
