open-afc-project/openafc

src/ratapi/ratapi/views/ratafc.py

Default flask access to ratdb creates too many DB connections (one per request, released only on request completion that takes a long timew if request goes to Worker). This crashes AFC on GCE (wher enumber of connections severely limited) Hence all ratafc ratdb lookups moved to scoped sessions (one created in _auth_ap(), another for reading AFC config, that deallocate connections immediately

60. Moving ratafc accessto ratdb to scoped sessions

---

rcache/rcache_db_async.py
src/afc-packages/rcache/rcache_db.py

It fixes database accesses crashes under high load

92. Adding pool_pre_ping=True to Rcache SqlAlchemy engine creation

---

helm/afc-int/values.yaml
rcache/Dockerfile
rcache/rcache_app.py
rcache/rcache_service.py
src/afc-packages/pkgs.rcache
tests/regression/docker-compose.yaml

Logged stuff:
- Enabling/disabling of update/invalidation/precomputation
- Invalidation requests
- Precomputation quota changes

97. Add ALS  logging of rcache-related events

---

.github/workflows/regressions-test-remote.yml

108 update-public-ip-action-of-regr-tests

---

src/README.md
src/web/package.json
src/web/src/app/RatAfc/RatAfc.tsx
src/web/yarn.lock

Documentation update, but then needed an update to Prettier local to match CI version and identify a format change in one file

Added description of RASDatabase.dat to open-afc/src/README.md.

---

rcache/rcache_db_async.py

128. Precompute ordered in most-recent-updated-first

---

database_readme.md

Documentation update only; no functional changes

134 additional update of database readme file

---

helm/README.md

Details on cluster organisation added, GCP deployment described
Closes #163

163. helm/README.md updated

---

afc_server/afc_server_compute.py

Qiueue iterator created in autoacknowledge mode.
Checked with RMQ Webui while load test was running in noncache mode
Closes #180

180. Acknowledging worker-to-afcserver RMQ messages

---

helm/afc-int/values.yaml

For convenient exposing on k3d platform.
Closes #182

182. Nodeport for webui added to rmq

---

helm/afc-int/values.yaml
src/afc-packages/pkgs.uls
tests/regression/docker-compose.yaml
uls/Dockerfile-uls_service
uls/uls_service.py

ALS log is performed for each download attempt. It contains script parameters, timing of various download stages and intermediate results.
Tested in docker-compose environment.
Closes #173

173. Adding ALS log to ULS downloads

---

als/Dockerfile.siphon
als/README.md
als/als_query.py
als/requirements.txt

- `log` subcommand improved
- `als` and `timezones` subcommand added
Seemingly works in Compose environment
Closes #175

175. als_query.py update

---

als/Dockerfile.siphon
als/als_query.py

- Compatibility warnings disabled
- Crash related to --verbose parameter fixed
- Support for ancient DSN environment variables (still used on afc.broeddcom.com) added
Closes #202

202 .als_query.py bugfixes

---

cert_db/requirements.txt
msghnd/requirements.txt
rat_server/requirements.txt
src/afc-packages/afcobjst/setup.py

210 fix python related dependabot issues

---

src/ratapi/ratapi/views/admin.py
src/ratapi/ratapi/views/ratapi.py

Following paths will become inaccessible without authorization
/fbrat/ratapi/v1/rulesetIds
/fbrat/ratapi/v1/regions
/fbrat/admin/user/frequency_range

Closing unauthorized access to some paths

---

dispatcher/nginx.conf.template

moved headers to the top of the locations
Cross-Origin-Opener-Policy added
secure attribute added to csrf_token

SECURITY: refactor nginx config

---

README.md
tools/editing/README.md

Updated readmes with typo corrections, reorganization, and updated docker compose and env files
Added how to use discussions to Contributing section

Updated readmes 

---

ReleaseNote.md
src/ratapi/ratapi/templates/flask_user_layout.html

There was an unneeded link to an old jQuery and bootstrap that was removed
Exercised UI: Updated configuration, exercised web page controls, ran a request, all functionality seems working

Remove unneeded jquery and bootstrap links

---

als/als_migrations/versions/2024_10_31-87a874c761f8_mtls_dn_table_added.py

Fixing ALS Alembic upgrade crash on als_siphon startup.
Now ALS Alembic upgrade passes just fine.
Closes #236

236. sa.JSONB changed to sa_pg.JSONB

---

afc_server/afc_server_app.py
uls/fs_afc.py

- fs_afc.py retrieves error message from AFC message processor and prints it tp log
- afc_server_app.py fixed typo that accidentally made X-Real-IP requred header in AFC request
Tested in compose environment
Closes #261

261. Fixing ULS download failure

---

grafana/templates/custom.ini
grafana/templates/provisioning/datasources/als.yaml
grafana/templates/provisioning/datasources/als_json.yaml
grafana/templates/provisioning/datasources/fs_state.yaml

$__file(filename) changed to $__file{filename}
Closes #271

271. Fixing use of $__file directives in Grafana-related Jinja templates

---

cert_db/Dockerfile
src/ratapi/ratapi/manage.py

- Response compression enabled
- User Agent changed on one, used in some browser
- Retries added (hardcoded - 5 retries with 5 second pause)
Closes #274

274. Resuscitation of FCC certificate downloading

---

src/afc-engine/AfcManager.cpp
src/afc-engine/cconst.cpp
src/afc-engine/polygon.cpp

Reverts open-afc-project/openafc#282

Revert "281. AFC Engine facelift"

---

tools/release/tag.sh

the change
1. updates latest docker container images names
2. cleans up  and sorts images
closes #317

317-update-toolsreleasetagsh-script

---

uls/Dockerfile-uls_service
uls/uls_service.py

For each external file error message in state database and ULS downloader healthcheck email made actionable
Close #343

343 Improve diegnostics on external file discrepancy
